version: '3.9'

services:
  grafana:
    image: grafana/grafana
    ports:
      - ${GRAFANA_PORT:?error}:3000
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:?error}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:?error}
    volumes:
      - grafana:/var/lib/grafana

  mariadb:
    image: mariadb
    ports:
      - ${DB_PORT:?error}:3306
    environment:
       MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
       MARIADB_DATABASE: ${DB_NAME:?error}
       MARIADB_USER: ${DB_USER:?error}
       MARIADB_PASSWORD: ${DB_PASSWORD?error}
    volumes:
      - logger_data:/var/lib/mysql

  notifier:
    build:
      context: .
      dockerfile: ./notifier/docker/Dockerfile
    depends_on:
      - kafka
    ports:
      - ${NOTIFIER_APP_PORT:?error}:3000
    volumes:
      - ./notifier:/app

  processor:
    build:
      context: .
      dockerfile: ./processor/docker/Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./processor:/app

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '${KAFKA_PORT:?error}:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '${ZOOKEEPER_PORT:?error}:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT:?error}

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - ${KAFKA_UI_PORT:?error}:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:${KAFKA_PORT}
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:${ZOOKEEPER_PORT}
    restart: always
    depends_on:
      - kafka

volumes:
  logger_data:
  grafana:
